services:
  consul:
    image: "consul:1.15.4"
    container_name: consul1

    ports:
      - "8500:8500"
    # network_mode: host

  mysql:
    image: "mysql:9"
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "product"

  redis:
    image: "redis:7"
    container_name: redis1
    ports:
      - "6379:6379"

