services:
  consul:
    image: "hashicorp/consul:1.20"
    container_name: gomall-consul1

    ports:
      - "8500:8500"
    # network_mode: host

  mysql:
    image: "mysql:9"

    container_name: gomall-mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "product"
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d

  redis:
    image: "redis:7"
    container_name: gomall-redis1
    ports:
      - "6379:6379"

  nats:
    image: "nats:2.10"
    container_name: gomall-nats1
    ports:
      - "4222:4222"
      - "8222:8222"