// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	home "gomall_study/app/frontend/biz/router/home"
	"github.com/cloudwego/hertz/pkg/app/server"
	auth "gomall_study/app/frontend/biz/router/auth"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	auth.Register(r)

	home.Register(r)
}
